# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(editable=False, to='django_achievements.Achievement'),
        ),
    ]
