# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20170228_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='likescount',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
