# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creationevent',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feed_creationevent_related', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
