# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20170209_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ugc_post_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
