# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_auto_20170209_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likescount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
