# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0006_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
