# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0007_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Post', max_length=256),
            preserve_default=False,
        ),
    ]
